# https://ko.build/configuration/
defaultBaseImage: ko.local/moxactl:latest
builds:
  - id: moxa
    dir: .
    main: ./cmd/moxa
    ldflags:
      - -X main.masterShardVersion={{.Env.MVERSION}}
      - -X main.subShardVersion={{.Env.SVERSION}}
