// This code was autogenerated from protoc-gen-dragonboat, do not edit.
package master_shard

import (
	"context"
	"fmt"
	"runtime/debug"

	sm "github.com/lni/dragonboat/v3/statemachine"
	"google.golang.org/protobuf/proto"

	"github.com/LilithGames/protoc-gen-dragonboat/runtime"
)

type IMasterShardDragonboatServer interface {
	Healthz(req *HealthzRequest) (*HealthzResponse, error)
	GetStateVersion(req *GetStateVersionRequest) (*GetStateVersionResponse, error)
	ListShards(req *ListShardsRequest) (*ListShardsResponse, error)
	GetShard(req *GetShardRequest) (*GetShardResponse, error)
	CreateShard(req *CreateShardRequest) (*CreateShardResponse, error)
	UpdateShard(req *UpdateShardRequest) (*UpdateShardResponse, error)
	DeleteShard(req *DeleteShardRequest) (*DeleteShardResponse, error)
}

type IMasterShardDragonboatClient interface {
	Healthz(ctx context.Context, req *HealthzRequest, opts ...runtime.DragonboatClientOption) (*HealthzResponse, error)
	GetStateVersion(ctx context.Context, req *GetStateVersionRequest, opts ...runtime.DragonboatClientOption) (*GetStateVersionResponse, error)
	ListShards(ctx context.Context, req *ListShardsRequest, opts ...runtime.DragonboatClientOption) (*ListShardsResponse, error)
	GetShard(ctx context.Context, req *GetShardRequest, opts ...runtime.DragonboatClientOption) (*GetShardResponse, error)
	CreateShard(ctx context.Context, req *CreateShardRequest, opts ...runtime.DragonboatClientOption) (*CreateShardResponse, error)
	UpdateShard(ctx context.Context, req *UpdateShardRequest, opts ...runtime.DragonboatClientOption) (*UpdateShardResponse, error)
	DeleteShard(ctx context.Context, req *DeleteShardRequest, opts ...runtime.DragonboatClientOption) (*DeleteShardResponse, error)
}

func DragonboatMasterShardLookup(s IMasterShardDragonboatServer, query interface{}) (result interface{}, err error) {
	defer func() {
		if perr := recover(); perr != nil {
			err = fmt.Errorf("panic: %v\nstacktrace from panic: %s", perr, string(debug.Stack()))
		}
	}()
	switch q := query.(type) {
	case *HealthzRequest:
		resp, err := s.Healthz(q)
		if err != nil {
			return resp, fmt.Errorf("IMasterShardServer.Healthz(%v) err: %w", q, err)
		}
		return resp, nil
	case *GetStateVersionRequest:
		resp, err := s.GetStateVersion(q)
		if err != nil {
			return resp, fmt.Errorf("IMasterShardServer.GetStateVersion(%v) err: %w", q, err)
		}
		return resp, nil
	case *ListShardsRequest:
		resp, err := s.ListShards(q)
		if err != nil {
			return resp, fmt.Errorf("IMasterShardServer.ListShards(%v) err: %w", q, err)
		}
		return resp, nil
	case *GetShardRequest:
		resp, err := s.GetShard(q)
		if err != nil {
			return resp, fmt.Errorf("IMasterShardServer.GetShard(%v) err: %w", q, err)
		}
		return resp, nil
	case *runtime.DragonboatVoid:
		// healthcheck
		return &runtime.DragonboatVoid{}, nil
	default:
		return nil, fmt.Errorf("%w(type: %T)", runtime.ErrUnknownRequest, q)
	}
}

func DragonboatMasterShardUpdateDispatch(s IMasterShardDragonboatServer, msg proto.Message) (result proto.Message, err error) {
	defer func() {
		if perr := recover(); perr != nil {
			err = fmt.Errorf("panic: %v\nstacktrace from panic: %s", perr, string(debug.Stack()))
		}
	}()
	switch m := msg.(type) {
	case *CreateShardRequest:
		resp, err := s.CreateShard(m)
		return resp, err
	case *UpdateShardRequest:
		resp, err := s.UpdateShard(m)
		return resp, err
	case *DeleteShardRequest:
		resp, err := s.DeleteShard(m)
		return resp, err
	case *runtime.DragonboatVoid:
		// dummy update increate index
		return &runtime.DragonboatVoid{}, nil
	default:
		return nil, fmt.Errorf("%w(type: %T)", runtime.ErrUnknownRequest, m)
	}
}

func DragonboatMasterShardUpdate(s IMasterShardDragonboatServer, data []byte) (sm.Result, error) {
	msg, err := runtime.ParseDragonboatRequest(data)
	if err != nil {
		return runtime.MakeDragonboatResult(nil, err), nil
	}
	resp, err := DragonboatMasterShardUpdateDispatch(s, msg)
	return runtime.MakeDragonboatResult(resp, err), nil
}

func DragonboatMasterShardConcurrencyUpdate(s IMasterShardDragonboatServer, entries []sm.Entry) ([]sm.Entry, error) {
	for i := range entries {
		entry := &entries[i]
		msg, err := runtime.ParseDragonboatRequest(entry.Cmd)
		if err != nil {
			entry.Result = runtime.MakeDragonboatResult(nil, err)
		} else {
			resp, err := DragonboatMasterShardUpdateDispatch(s, msg)
			entry.Result = runtime.MakeDragonboatResult(resp, err)
		}
	}
	return entries, nil
}

type MasterShardDragonboatClient struct {
	client runtime.IDragonboatClient
}

func NewMasterShardDragonboatClient(client runtime.IDragonboatClient) IMasterShardDragonboatClient {
	return &MasterShardDragonboatClient{client: client}
}
func (it *MasterShardDragonboatClient) Healthz(ctx context.Context, req *HealthzRequest, opts ...runtime.DragonboatClientOption) (*HealthzResponse, error) {
	resp, err := it.client.Query(ctx, req, opts...)
	if r, ok := resp.(*HealthzResponse); ok {
		return r, err
	} else if err != nil {
		return nil, err
	} else {
		return nil, fmt.Errorf("cannot parse %T response type to *HealthzResponse", resp)
	}
}
func (it *MasterShardDragonboatClient) GetStateVersion(ctx context.Context, req *GetStateVersionRequest, opts ...runtime.DragonboatClientOption) (*GetStateVersionResponse, error) {
	resp, err := it.client.Query(ctx, req, opts...)
	if r, ok := resp.(*GetStateVersionResponse); ok {
		return r, err
	} else if err != nil {
		return nil, err
	} else {
		return nil, fmt.Errorf("cannot parse %T response type to *GetStateVersionResponse", resp)
	}
}
func (it *MasterShardDragonboatClient) ListShards(ctx context.Context, req *ListShardsRequest, opts ...runtime.DragonboatClientOption) (*ListShardsResponse, error) {
	resp, err := it.client.Query(ctx, req, opts...)
	if r, ok := resp.(*ListShardsResponse); ok {
		return r, err
	} else if err != nil {
		return nil, err
	} else {
		return nil, fmt.Errorf("cannot parse %T response type to *ListShardsResponse", resp)
	}
}
func (it *MasterShardDragonboatClient) GetShard(ctx context.Context, req *GetShardRequest, opts ...runtime.DragonboatClientOption) (*GetShardResponse, error) {
	resp, err := it.client.Query(ctx, req, opts...)
	if r, ok := resp.(*GetShardResponse); ok {
		return r, err
	} else if err != nil {
		return nil, err
	} else {
		return nil, fmt.Errorf("cannot parse %T response type to *GetShardResponse", resp)
	}
}
func (it *MasterShardDragonboatClient) CreateShard(ctx context.Context, req *CreateShardRequest, opts ...runtime.DragonboatClientOption) (*CreateShardResponse, error) {
	resp, err := it.client.Mutate(ctx, req, opts...)
	if r, ok := resp.(*CreateShardResponse); ok {
		return r, err
	} else if err != nil {
		return nil, err
	} else {
		return nil, fmt.Errorf("cannot parse %T response type to *CreateShardResponse", resp)
	}
}
func (it *MasterShardDragonboatClient) UpdateShard(ctx context.Context, req *UpdateShardRequest, opts ...runtime.DragonboatClientOption) (*UpdateShardResponse, error) {
	resp, err := it.client.Mutate(ctx, req, opts...)
	if r, ok := resp.(*UpdateShardResponse); ok {
		return r, err
	} else if err != nil {
		return nil, err
	} else {
		return nil, fmt.Errorf("cannot parse %T response type to *UpdateShardResponse", resp)
	}
}
func (it *MasterShardDragonboatClient) DeleteShard(ctx context.Context, req *DeleteShardRequest, opts ...runtime.DragonboatClientOption) (*DeleteShardResponse, error) {
	resp, err := it.client.Mutate(ctx, req, opts...)
	if r, ok := resp.(*DeleteShardResponse); ok {
		return r, err
	} else if err != nil {
		return nil, err
	} else {
		return nil, fmt.Errorf("cannot parse %T response type to *DeleteShardResponse", resp)
	}
}
