// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: cluster/config.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrationPolicy int32

const (
	MigrationPolicy_Auto   MigrationPolicy = 0
	MigrationPolicy_Always MigrationPolicy = 1
	MigrationPolicy_Never  MigrationPolicy = 2
)

// Enum value maps for MigrationPolicy.
var (
	MigrationPolicy_name = map[int32]string{
		0: "Auto",
		1: "Always",
		2: "Never",
	}
	MigrationPolicy_value = map[string]int32{
		"Auto":   0,
		"Always": 1,
		"Never":  2,
	}
)

func (x MigrationPolicy) Enum() *MigrationPolicy {
	p := new(MigrationPolicy)
	*p = x
	return p
}

func (x MigrationPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_config_proto_enumTypes[0].Descriptor()
}

func (MigrationPolicy) Type() protoreflect.EnumType {
	return &file_cluster_config_proto_enumTypes[0]
}

func (x MigrationPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationPolicy.Descriptor instead.
func (MigrationPolicy) EnumDescriptor() ([]byte, []int) {
	return file_cluster_config_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeHostDir     string          `protobuf:"bytes,1,opt,name=node_host_dir,json=nodeHostDir,proto3" json:"node_host_dir,omitempty"`
	LocalStorageDir string          `protobuf:"bytes,2,opt,name=local_storage_dir,json=localStorageDir,proto3" json:"local_storage_dir,omitempty"`
	MemberSeed      []string        `protobuf:"bytes,3,rep,name=member_seed,json=memberSeed,proto3" json:"member_seed,omitempty"`
	RecoveryMode    bool            `protobuf:"varint,4,opt,name=recovery_mode,json=recoveryMode,proto3" json:"recovery_mode,omitempty"`
	MigrationPolicy MigrationPolicy `protobuf:"varint,5,opt,name=migration_policy,json=migrationPolicy,proto3,enum=cluster.MigrationPolicy" json:"migration_policy,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_cluster_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetNodeHostDir() string {
	if x != nil {
		return x.NodeHostDir
	}
	return ""
}

func (x *Config) GetLocalStorageDir() string {
	if x != nil {
		return x.LocalStorageDir
	}
	return ""
}

func (x *Config) GetMemberSeed() []string {
	if x != nil {
		return x.MemberSeed
	}
	return nil
}

func (x *Config) GetRecoveryMode() bool {
	if x != nil {
		return x.RecoveryMode
	}
	return false
}

func (x *Config) GetMigrationPolicy() MigrationPolicy {
	if x != nil {
		return x.MigrationPolicy
	}
	return MigrationPolicy_Auto
}

var File_cluster_config_proto protoreflect.FileDescriptor

var file_cluster_config_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22,
	0xe3, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x44, 0x69, 0x72, 0x12, 0x2a,
	0x0a, 0x11, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f,
	0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x69, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x43, 0x0a, 0x10, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x52, 0x0f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2a, 0x32, 0x0a, 0x0f, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x6f,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x4e, 0x65, 0x76, 0x65, 0x72, 0x10, 0x02, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x69, 0x6c, 0x69, 0x74, 0x68, 0x47, 0x61,
	0x6d, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x78, 0x61, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cluster_config_proto_rawDescOnce sync.Once
	file_cluster_config_proto_rawDescData = file_cluster_config_proto_rawDesc
)

func file_cluster_config_proto_rawDescGZIP() []byte {
	file_cluster_config_proto_rawDescOnce.Do(func() {
		file_cluster_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_cluster_config_proto_rawDescData)
	})
	return file_cluster_config_proto_rawDescData
}

var file_cluster_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cluster_config_proto_goTypes = []interface{}{
	(MigrationPolicy)(0), // 0: cluster.MigrationPolicy
	(*Config)(nil),       // 1: cluster.Config
}
var file_cluster_config_proto_depIdxs = []int32{
	0, // 0: cluster.Config.migration_policy:type_name -> cluster.MigrationPolicy
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_config_proto_init() }
func file_cluster_config_proto_init() {
	if File_cluster_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cluster_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cluster_config_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_config_proto_goTypes,
		DependencyIndexes: file_cluster_config_proto_depIdxs,
		EnumInfos:         file_cluster_config_proto_enumTypes,
		MessageInfos:      file_cluster_config_proto_msgTypes,
	}.Build()
	File_cluster_config_proto = out.File
	file_cluster_config_proto_rawDesc = nil
	file_cluster_config_proto_goTypes = nil
	file_cluster_config_proto_depIdxs = nil
}
