// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: cluster/snapshot.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index      uint64            `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Version    string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path       string            `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	NodeHostId string            `protobuf:"bytes,4,opt,name=node_host_id,json=nodeHostId,proto3" json:"node_host_id,omitempty"`
	Nodes      map[uint64]string `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RemoteSnapshot) Reset() {
	*x = RemoteSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteSnapshot) ProtoMessage() {}

func (x *RemoteSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteSnapshot.ProtoReflect.Descriptor instead.
func (*RemoteSnapshot) Descriptor() ([]byte, []int) {
	return file_cluster_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteSnapshot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RemoteSnapshot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RemoteSnapshot) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoteSnapshot) GetNodeHostId() string {
	if x != nil {
		return x.NodeHostId
	}
	return ""
}

func (x *RemoteSnapshot) GetNodes() map[uint64]string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_cluster_snapshot_proto protoreflect.FileDescriptor

var file_cluster_snapshot_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x22, 0xea, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6e, 0x6f, 0x64, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x25,
	0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x69, 0x6c,
	0x69, 0x74, 0x68, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x78, 0x61, 0x2f, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cluster_snapshot_proto_rawDescOnce sync.Once
	file_cluster_snapshot_proto_rawDescData = file_cluster_snapshot_proto_rawDesc
)

func file_cluster_snapshot_proto_rawDescGZIP() []byte {
	file_cluster_snapshot_proto_rawDescOnce.Do(func() {
		file_cluster_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_cluster_snapshot_proto_rawDescData)
	})
	return file_cluster_snapshot_proto_rawDescData
}

var file_cluster_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cluster_snapshot_proto_goTypes = []interface{}{
	(*RemoteSnapshot)(nil), // 0: cluster.RemoteSnapshot
	nil,                    // 1: cluster.RemoteSnapshot.NodesEntry
}
var file_cluster_snapshot_proto_depIdxs = []int32{
	1, // 0: cluster.RemoteSnapshot.nodes:type_name -> cluster.RemoteSnapshot.NodesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_snapshot_proto_init() }
func file_cluster_snapshot_proto_init() {
	if File_cluster_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cluster_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cluster_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_snapshot_proto_goTypes,
		DependencyIndexes: file_cluster_snapshot_proto_depIdxs,
		MessageInfos:      file_cluster_snapshot_proto_msgTypes,
	}.Build()
	File_cluster_snapshot_proto = out.File
	file_cluster_snapshot_proto_rawDesc = nil
	file_cluster_snapshot_proto_goTypes = nil
	file_cluster_snapshot_proto_depIdxs = nil
}
