apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: default
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: proxy
    spec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Always
      containers:
        - name: proxy
          image: ko://github.com/LilithGames/moxa/cmd/moxa-proxy
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
spec:
  selector:
    app: proxy
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001

---
