apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-moxa
  namespace: temp
spec:
  storageClassName: alicloud-nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
