// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: utils/sync.proto

package utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStateType int32

const (
	SyncStateType_Add    SyncStateType = 0
	SyncStateType_Update SyncStateType = 1
	SyncStateType_Remove SyncStateType = 2
)

// Enum value maps for SyncStateType.
var (
	SyncStateType_name = map[int32]string{
		0: "Add",
		1: "Update",
		2: "Remove",
	}
	SyncStateType_value = map[string]int32{
		"Add":    0,
		"Update": 1,
		"Remove": 2,
	}
)

func (x SyncStateType) Enum() *SyncStateType {
	p := new(SyncStateType)
	*p = x
	return p
}

func (x SyncStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_utils_sync_proto_enumTypes[0].Descriptor()
}

func (SyncStateType) Type() protoreflect.EnumType {
	return &file_utils_sync_proto_enumTypes[0]
}

func (x SyncStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStateType.Descriptor instead.
func (SyncStateType) EnumDescriptor() ([]byte, []int) {
	return file_utils_sync_proto_rawDescGZIP(), []int{0}
}

var File_utils_sync_proto protoreflect.FileDescriptor

var file_utils_sync_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2a, 0x30, 0x0a, 0x0d, 0x53, 0x79, 0x6e,
	0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x64,
	0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x02, 0x42, 0x23, 0x5a, 0x21, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x69, 0x6c, 0x69, 0x74, 0x68,
	0x47, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x78, 0x61, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_utils_sync_proto_rawDescOnce sync.Once
	file_utils_sync_proto_rawDescData = file_utils_sync_proto_rawDesc
)

func file_utils_sync_proto_rawDescGZIP() []byte {
	file_utils_sync_proto_rawDescOnce.Do(func() {
		file_utils_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_utils_sync_proto_rawDescData)
	})
	return file_utils_sync_proto_rawDescData
}

var file_utils_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_utils_sync_proto_goTypes = []interface{}{
	(SyncStateType)(0), // 0: utils.SyncStateType
}
var file_utils_sync_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utils_sync_proto_init() }
func file_utils_sync_proto_init() {
	if File_utils_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_utils_sync_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utils_sync_proto_goTypes,
		DependencyIndexes: file_utils_sync_proto_depIdxs,
		EnumInfos:         file_utils_sync_proto_enumTypes,
	}.Build()
	File_utils_sync_proto = out.File
	file_utils_sync_proto_rawDesc = nil
	file_utils_sync_proto_goTypes = nil
	file_utils_sync_proto_depIdxs = nil
}
